### ISSUE TITLE
Getting undefined keys of a socket from dht connection

### ISSUE THREAD

**Issue by zacharygriffee** [holepunchto/hyperswarm#157]
Hello!

During the _handleServerConnection (https://github.com/holepunchto/hyperswarm/blob/caf59d7b40981f975eb0b260d565acd08e5d2b15/index.js#L275C86-L275C86), when a socket reconnects, the conn.publicKey is undefined causing a fail

Other things to note, I am running other DHT operations on the same node as the swarm is operating on, not sure if that could cause problems. I am also running operations through the DHT WebSocket Relay. Everything is fine up until a socket tries to reconnect.

edit: sorry for all the edits, long night.

![image](https://github.com/holepunchto/hyperswarm/assets/5599507/5667f012-836e-4ef2-9eb9-e728ad7b38d3)

**Comment by mafintosh** [comment]
From the stack above you are not using plain hyperswarm (ie there is a websocket involved in your stack)

The remotePublicKey is never null nor undefined in vanilla. I suggest you open the issue on the “custom” provider you are using

**Comment by mafintosh** [comment]
Ie the websocket relay after rereading your message. Just ping me there is thats a holepunch project also
