### ISSUE TITLE
Hole punching with a mobile connection and carrier grade nat

### ISSUE THREAD

**Issue by atbentley** [holepunchto/hyperswarm#63]
Looks like the hole punching in beaker browser (and presumable hyperswarm?) does not support networks using carrier grade nat (CGN / CGNAT).

Mobile connections (3G / 4G / LTE / 5G) are commonly put behind carrier grade nats.

I'm opening this issue to track what the project's intentions are in supporting hole punching for devices on these types of networks, so that other people searching can stumble on this.

**Comment by davidmarkclements** [comment]
personally I think that would a super awesome thing to have,  I also wouldn't know where to start. Any extra info highly welcome

**Comment by atbentley** [comment]
For those following along on github, @mafintosh and I spent some time debugging this over on discord. We were able to get hole punching working on my connection with some hacked together scripts.

**Comment by innerexception** [comment]
🙏 📿

**Comment by wolfsgrove** [comment]
Any progress on this?

**Comment by mafintosh** [comment]
Mobile connections work fine. Double randomised nats is the only case it doesn’t support in latest major
